### ISSUE TITLE
Command-on-entry flag is not triggered when joining the game

### ISSUE THREAD

**Issue by TheoRetisch1** [Invvk/WorldGuardExtraFlags#15]
### Server Implementation

Paper

### Server Version

1.17.1

### Describe the bug

The flag command-on-entry is not triggered when a player logs in and arrives in the corresponding region, e.g. by a relog. A teleport into a region works fine, on the other hand. It would be great if the flag would also execute the command when a player joins the game and arrives in the region.

### To Reproduce

1. Create a worldguard region.
2. /rg flag <region> command-on-entry </command>
3. Enter the region and teleport into the region -> everything works fine
4. Relog in the region -> the command-on-entry is not triggered.

### Expected behaviour

The flag command-on-entry should be triggered when a player joins the server and arrives in the corresponding region.

### WGEF-Reborn version

WGEF-Reborn version 2.1.5

### Checklist

- [X] I'm using java 16+ and running my server in 1.17.1+
- [X] I am using the newest build from https://github.com/Invvk/WorldGuardExtraFlagsPlugin/releases and the issue still persists.

### Anything else?

Thanks for continuing the project!

**Comment by Invvk** [comment]
Should drop an update today

**Comment by TheoRetisch1** [comment]
Wow, that's quick thank you! 🥇

**Comment by Invvk** [comment]
added in 733226a
