### ISSUE TITLE
The give-effect flag pauses all effects regardless of the region effects

### ISSUE THREAD

**Issue by TheoRetisch1** [Invvk/WorldGuardExtraFlags#18]
### Server Implementation

Paper

### Server Version

1.17.1

### Describe the bug

If you enter a region in which the `give-effect` flag is active, all effects that you had before entering the region are paused. If you leave the region, they are set again with the correct strength and length. This behaviour should only apply to effects that are already given by the region and not to all effects.

### To Reproduce

1. Create a worldguard region
2. /rg flag <region> give-effects fast_digging 1
3. Drink a night vision potion and give yourself the fast_digging effect.
4. Enter the region -> all effects are paused while you get the effects of the region

### Expected behaviour

The night vision effect should continue while the fast_digging effect should be paused until you leave the region again. Only those effects should be paused that are also assigned by the region.

### WGEF-Reborn version

WGEF-Reborn version 2.1.7

### Checklist

- [X] I'm using java 16+ and running my server in 1.17.1+
- [X] I am using the newest build from https://github.com/Invvk/WorldGuardExtraFlagsPlugin/releases and the issue still persists.

**Comment by Invvk** [comment]
AFAIK This was the behavior that the old plugin followed. Or maybe I mixed things up with block-effects

**Comment by TheoRetisch1** [comment]
The differentiation between the effects that need to be paused works using `WorldGuardExtraFlags version 4.1.5-SNAPSHOT` under the same setup. I think you really mixed it up with the `blocked-effects`, the paused effect differentiation has worked for quite some time in the old plugin.

**Comment by Invvk** [comment]
Should drop an update today.

**Comment by Invvk** [comment]
Patched in 6a4adfe. The plugin now only removes the effects that the flag has. as an example if the player have speed and night vision potion effect and the `give-effect` flag has only speed potion, The plugin will only remove speed on entry. on exit it will give it back. However, the player can still drink speed potion inside the region and this will override the speed potion given by the flag. to counter this, add speed to `blocked-effects` and this should stop players from overriding the potion effects given by `give-effects`

**Comment by TheoRetisch1** [comment]
Thank you! 👍
