### ISSUE TITLE
Error - could not pass event PlayerMoveEvent

### ISSUE THREAD

**Issue by TheoRetisch1** [Invvk/WorldGuardExtraFlags#23]
### Server Implementation

Paper

### Server Version

1.17.1

### Describe the bug

Ever since I started using the latest version `2.1.8`, I regularly get the following errors in the log `Could not pass event PlayerMoveEvent to WorldGuard v7.0.7-SNAPSHOT+2156-9b66513`, filling hundreds of lines. Here is the full stacktrace: https://pastebin.com/zXtnka1s. I couldn't really pinpoint the cause in-game and no ingame errors were reported. But it spams quite a bit.

### To Reproduce

1. Use WorldGuardExtraFlags Reborn 2.1.8
2. Play for a while and take a look at the log

### Expected behaviour

No errors

### Error log (if applicable)

https://pastebin.com/zXtnka1s

### WGEF-Reborn version

WGEF-Reborn version 2.1.8

### Checklist

- [X] I'm using java 16+ and running my server in 1.17.1+
- [X] I am using the newest build from https://github.com/Invvk/WorldGuardExtraFlagsPlugin/releases and the issue still persists.

**Comment by Invvk** [comment]
It's an issue related to `give-effect` flag changes. Should drop an update today to patch it.

**Comment by Invvk** [comment]
patched in f603d11, sorry it took too long
