### ISSUE TITLE
Trees gets cut between owned/unowned regions

### ISSUE THREAD

**Issue by TNTUP** [Invvk/WorldGuardExtraFlags#36]
### Server Implementation

Paper

### Server Version

1.17.1

### Describe the bug

When you plant saplings and let them grow, they will get cut at the border of the region (see Screenshot 1) and its expected to let it grow fully even otuside of the region (Screenshot 2)

### To Reproduce

1. Set flags in __global__ as you want to deny players building there
2. Create a region enough to plant a sapling next to the region's border and grow it. 
3. See it gets cut in half (missing leaves or logs) with the plugin WGEF-Reborn enabled.
4. Remove the plugin and repeat the same steps (see screenshot 1)

### Expected behaviour

Expected to see the tree fully grown despite it goes outside (intended with WG so no issues)

### Screenshots / Videos

Expected: ![exhibit1](https://i.qcfb.ca/20211120165512.png)

Notice the line and the dotted 1 and 2 denotes there's a region in the (2) marker which (1) has no region (aka __global__)

Result: ![exhibit 2](https://i.qcfb.ca/20211120165607.png)

Notice the line and the dotted 1 and 2 denotes there's 2 regions beneath them, the player who reported me has access to both regions (We'Re using Landlord for claim management and it creates WG regions per chunk)

### WGEF-Reborn version

WGEF-Reborn version 2.2.0

### Checklist

- [X] I'm using java 16+ and running my server in 1.17.1+
- [X] I am using the newest build from https://github.com/Invvk/WorldGuardExtraFlagsPlugin/releases and the issue still persists.

**Comment by Invvk** [comment]
The thing is, there isn’t really a way to check for this stuff. if the tree grew by natural causes then it is impossible to tell who planted it. If it was grown by a player then it is possible but it is a heavy operation. In order for this to be completely patched was by to remove all flags related to allow / deny block place / break.
Further more, I don’t believe that this issue will be ever resolved from my part. I did the best that I could to make this issue disappear but it’s out of my hand. WG Developers are the key to solve this issue.

The only thing I can offer is to add an option to disable the flags that causes the break.

Note: I’ve also heard that WG are planning to add similar flags to the allow/deny block place/break, but till now they have not done it yet even tho that there is a PR waiting to be merged.

**Comment by TNTUP** [comment]
so it means I will downgrade the plugin as it worked before this patch :< Thanks anyway

**Comment by Invvk** [comment]
> so it means I will downgrade the plugin as it worked before this patch :< Thanks anyway

You mean it worked in 2.1.9 or in the original plugin?

**Comment by TNTUP** [comment]
> > so it means I will downgrade the plugin as it worked before this patch :< Thanks anyway
> 
> You mean it worked in 2.1.9 or in the original plugin?

Can't recall if it did work before. Last version was 2.1.9 (checked in logs) and until now someones notices and report me that. Guess either live with that as I need this plugin on the server. Tried down to 2.1.6 and no luck.

Oh well. Thanks for your time and I'll keep an eye on WG's side if they decide to implement those flags in the future^^
