### ISSUE TITLE
command-on-entry & command-on-exit doesnt work

### ISSUE THREAD

**Issue by Hyronymos1337** [Invvk/WorldGuardExtraFlags#78]
### Server Implementation

Purpur

### Server Version

1.18.1

### Describe the bug

the flags command-on-entry & command-on-exit doesnt work

### To Reproduce

create a region with a command-on-entry & command-on-exit doesnt work flag and a command (like /warp pvp %username%)

### Expected behaviour

.....

### WGEF-Reborn version

WGEF-Reborn 2.3-stable+6cd8b68

### Checklist

- [X] I'm using java 16+ and running my server in 1.17+
- [X] I am using the newest build from https://www.spigotmc.org/resources/96894/ and the issue still persists.

**Comment by lordhadow1** [comment]
https://gyazo.com/e7449fc916a7511e5278f049defb48cf

**Comment by lordhadow1** [comment]
![image](https://user-images.githubusercontent.com/73142735/165870226-192be0a7-2a3a-4b70-ad9e-d855aad9785d.png)
