### ISSUE TITLE
Flag allow-entity-destroy and allow-entity-damage doesn't work with arrows

### ISSUE THREAD

**Issue by SrBedrock** [Invvk/WorldGuardExtraFlags#80]
### Server Implementation

Paper

### Server Version

1.18.1

### Describe the bug

When using the `allow-entity-damage` and `allow-entity-destroy` flag, it is not possible to break ender crystals using arrows.

It is possible to break using the fists.

### To Reproduce

1. Create a protection on the main island of the end.
2. Use the command:
`/rg flag -w "world_the_end" <region> allow-entity-damage ENDER_CRYSTAL` 
`/rg flag -w "world_the_end" <region> allow-entity-destroy ENDER_CRYSTAL`
3. Summon the Ender Dragon with ender crystals
4. Try to destroy the ender crystals using bow and arrow

### Expected behaviour

Being able to break ender crystals with bow and arrow.

### Screenshots / Videos

https://user-images.githubusercontent.com/51332006/166329727-25583679-c93f-4659-9cbe-9b0ccbe93a3e.mp4

### WGEF-Reborn version

WGEF-Reborn version 2.5-stable+bca609f

### Checklist

- [X] I'm using java 16+ and running my server in 1.17+
- [X] I am using the newest build from https://www.spigotmc.org/resources/96894/ and the issue still persists.

**Comment by Invvk** [comment]
This bug is interesting. even though it is detecting me as the damage cause, it still denies the change which is quite weird.

I will look further into it and see what is causing this behavior.

**Comment by Invvk** [comment]
https://github.com/Invvk/WorldGuardExtraFlags/blob/4d19c16de0cb27fe9f52b32f4fc980b2a024e221/WGEF-Core/src/main/java/io/github/invvk/wgef/listeners/EntityBreakListener.java#L29

Issue found. The original damager has to be a player, and because the damage is not directly caused by a player (AKA caused by the arrow) the event is simply ignored. Looking into a couple of possible fixs

**Comment by SrBedrock** [comment]
Problem solved with PR #81
