### ISSUE TITLE
respawn-location flag

### ISSUE THREAD

**Issue by TheoRetisch1** [Invvk/WorldGuardExtraFlags#83]
### What feature do you want to see added?

Could you please bring the respawn-location flag from the original plugin back. The flag sets the players respawn location when inside a region. The flag was very useful for events and mini-games. Players could be respawned at specific locations for a great gaming experience.

### Are there any alternatives?

I' m not aware of any alternatives.

**Comment by Invvk** [comment]
WorldGuard already has a similar flag to `respawn-location`

it can be found here: https://worldguard.enginehub.org/en/latest/regions/flags/#movement 
`spawn` flag
