### ISSUE TITLE
Operators don't get night vision effect with give-effects flag

### ISSUE THREAD

**Issue by IveMalfunctioned** [Invvk/WorldGuardExtraFlags#88]
### Server Implementation

Spigot

### Server Version

1.18.1

### Describe the bug

Operators don't get night vision because of the worldguard bypass permission they have. Maybe add a switch to the give-effects flag to affect OPs or not (if that's possible)?

### To Reproduce

1. make a region
2. rg flag name give-effects night_vision
3. stand in the region
4. op and deop yourself and see

### Expected behaviour

I want anyone to have night vision in the region, regardless of operator status

### WGEF-Reborn version

WGEF-Reborn version 2.6-stable+73c8022

### Checklist

- [X] I'm using java 16+ and running my server in 1.17+
- [X] I am using the newest build from https://www.spigotmc.org/resources/96894/ and the issue still persists.

### Anything else?

nah

**Comment by Invvk** [comment]
This is not an issue, but rather an intended behavior for all flags.
However, this behavior will be change in the future.

**Comment by IveMalfunctioned** [comment]
> Maybe add a switch to the give-effects flag to affect OPs or not (if that's possible)?

?
